aliases:

- &install-node-dependencies
    |
    yarn

defaults: &defaults
  working_directory: ~/rainbow

jobs:
  test-ios:
    <<: *defaults
    macos:
      xcode: "10.2"
    dependencies:
      pre:

    steps:
    - checkout
    - run:
        name: Load dependencies
        command:
          |
          brew update
          brew tap wix/brew
          brew install --HEAD applesimutils
          npm install -g detox-cli
    - run: *install-node-dependencies
    - run: detox build | awk '{print $1}'
    - run: detox test

workflows:
  version: 2

  build:
    jobs:
    - test-ios
